### ISSUE TITLE
Fix Project Directories

### ISSUE THREAD

**Issue by Rekkonnect** [Rekkonnect/GenericsAnalyzer#1]
Upon the solution's creation, the 5 initial projects (all but `GenericsAnalyzer.Core`) were included in a `GenericsAnalyzer` directory, instead of being in the solution's root directory. For consistency (and to avoid some notable VS bugs when it comes to project dependencies), it would be good if they were all migrated to the root solution directory.

**Comment by AlFasGD** [comment]
This will have an impact on the Actions config file, ensure that it is properly modified to reflect the new project locations.

**Comment by Rekkonnect** [comment]
Upon the migration to https://github.com/RossLean/RossLean/ this is taken care of.
